name: CMake Build

on:
  push:
    branches: [ "testCI" ]
  pull_request:
    branches: [ "testCI" ]

env:
  LIBZMQ_VERSION: 4.3.5
  CPPZMQ_VERSION: 4.11.0
  THREADS: 2

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Get libzmq
        run: |
          curl -L https://github.com/zeromq/libzmq/archive/refs/tags/v${{ env.LIBZMQ_VERSION }}.tar.gz -o libzmq.tar.gz
          tar -xvzf libzmq.tar.gz

      - name: Build libzmq
        run: |
          cmake -S libzmq-${{ env.LIBZMQ_VERSION }} -B libzmq-build \
            -DWITH_PERF_TOOL=OFF \
            -DZMQ_BUILD_TESTS=OFF \
            -DLIBZMQ_WERROR=OFF \
            -DENABLE_DRAFTS=OFF \
            -DENABLE_CURVE=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build libzmq-build --config ${{ matrix.build_type }} -j ${{ env.THREADS }}
          echo "LIBZMQ=${PWD}/libzmq-build" >> ${GITHUB_ENV}

      - name: Get cppzmq
        run: |
          curl -L https://github.com/zeromq/cppzmq/archive/refs/tags/v${{ env.CPPZMQ_VERSION }}.tar.gz -o cppzmq.tar.gz
          tar -xvzf cppzmq.tar.gz

      - name: Build cppzmq
        env:
          CMAKE_PREFIX_PATH: ${{ env.LIBZMQ }}
        run: |
          cmake -S cppzmq-${{ env.CPPZMQ_VERSION }} -B cppzmq-build \
            -DCPPZMQ_BUILD_TESTS=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build cppzmq-build --config ${{ matrix.build_type }} -j ${{ env.THREADS }}
          echo "CPPZMQ=${PWD}/cppzmq-build" >> ${GITHUB_ENV}

      - name: Build cppzmqzoltanext
        env:
          CMAKE_PREFIX_PATH: ${{ env.LIBZMQ }}:${{ env.CPPZMQ }}
        run: |
          cmake -S . -B build \
            -DCZZE_BUILD_TESTS=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build --config ${{ matrix.build_type }} -j ${{ env.THREADS }}

      - name: Run Tests
        run: |
          ctest --test-dir build --build-config ${{ matrix.build_type }} --output-on-failure
